spring:
  application:
    name: activity-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fitness_activity_db
      database: fitness_activity_db
server:
  port: 5001

# to locate eureka server
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://localhost:5002/eureka/ # our eureka server host