spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/fitness_user_db
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 5000

# to locate eureka server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5002/eureka/ # our eureka server host